
# Singleton service factory configuration/IoC injection
singletons:

#Services

#------------ Other Configurations  ------------
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - com.fic.PathHandlerProvider
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
#- com.networknt.server.StartupHookProvider:
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
# - com.networknt.server.ShutdownHookProvider:
  # - com.networknt.server.Test1ShutdownHook
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
- com.networknt.handler.MiddlewareHandler:
#Validator Validate request based on swagger specification (depending on Swagger and Body)
#com.networknt.validator.ValidatorHandler
#Sanitizer Encode cross site scripting
#  - com.fic.handler.PrometheusHandler
#SimpleAudit Log important info about the request into audit log
#  - com.networknt.audit.AuditHandler
#  - com.fic.handler.AuditHandler
#Body Parse body based on content type filter the header.
  - com.fic.BodyHandler
#Security JWT token verification and scope verification (depending on SwaggerHandler)
#  - com.networknt.security.JwtVerifyHandler
#Swagger Parsing swagger specification based on request uri and method.
#com.networknt.swagger.SwaggerHandler
#Cors handler to handler post/put pre-flight
#  - com.networknt.cors.CorsHttpHandler
#Correlation Create correlationId if it doesn't exist filter the request header and put it into the request header
#com.networknt.correlation.CorrelationHandler
#Traceability Put traceabilityId into response header from request header if it exists
#com.networknt.traceability.TraceabilityHandler
#Metrics In order to calculate response time accurately, this needs to be the second.
#com.networknt.metrics.MetricsHandler
#Exception Global exception handler that needs to be called first.
  - com.networknt.exception.ExceptionHandler
#
#  # Exception Global exception handler that needs to be called first to wrap all middleware handlers and business handlers
#  - com.networknt.exception.ExceptionHandler
#  # Metrics handler to calculate response time accurately, this needs to be the second handler in the chain.
#  - com.networknt.metrics.MetricsHandler
#  # Traceability Put traceabilityId into response header from request header if it exists
#  - com.networknt.traceability.TraceabilityHandler
#  # Correlation Create correlationId if it doesn't exist in the request header and put it into the request header
#  - com.networknt.correlation.CorrelationHandler
#  # Swagger Parsing swagger specification based on request uri and method.
#  - com.networknt.swagger.SwaggerHandler
#  # Security JWT token verification and scope verification (depending on SwaggerHandler)
#  - com.networknt.security.JwtVerifyHandler
#  # Body Parse body based on content type in the header.
#  - com.networknt.body.BodyHandler
#  # SimpleAudit Log important info about the request into audit log
#  - com.networknt.audit.AuditHandler
#  # Sanitizer Encode cross site scripting
#  - com.networknt.sanitizer.SanitizerHandler
#  # Validator Validate request based on swagger specification (depending on Swagger and Body)
#  - com.networknt.validator.ValidatorHandler





