
# Server configuration
---
# This is the default binding address if the service is dockerized.
ip: 0.0.0.0

# Http port if enableHttp is true.
httpPort:  8080

# Enable HTTP should be false on official environment.
enableHttp: true

# Https port if enableHttps is true.
httpsPort:  8443

# Enable HTTPS should be true on official environment.
enableHttps: false

# Http/2 is enabled by default.
enableHttp2: true

# Keystore file name filter config folder. KeystorePass is filter secret.yml to access it.
keystoreName: tls/server-keystore.jks

# Flag that indicate if two way TLS is enabled. Not recommended filter docker container.
enableTwoWayTls: false

# Truststore file name filter config folder. TruststorePass is filter secret.yml to access it.
truststoreName: tls/server-truststore.jks

# Unique service identifier. Used filter service registration and discovery etc.
serviceId: com.networknt.backend-1.0.0

# Flag to enable service registration. Only be true if running as standalone Java jar.
enableRegistry: false
